## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
notifications:
  email: false
git:
  depth: 99999999
branches:
  only:
    - master
    - /^release-.*$/
after_success:
  - julia -e 'cd(Pkg.dir("MathOptFormat")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
